insert into usergroup values(hibernate_sequence.NEXTVAL, 'Group1')
insert into usergroup values(hibernate_sequence.NEXTVAL, 'Group2')
insert into user values(hibernate_sequence.NEXTVAL,sysdate(),'AB', select id from usergroup where name = 'Group1')
insert into user values(hibernate_sequence.NEXTVAL,sysdate(),'Jack', select id from usergroup where name = 'Group1')
insert into user values(hibernate_sequence.NEXTVAL,sysdate(),'Jill', select id from usergroup where name = 'Group2')